export const Images = {
  logo: require("./images/logo-light.png"),
  dark_logo: require("./images/logo-dark.png"),
  light_logo: require("./images/logo-light.png"),
  splash_img: require("./images/splash_img.png"),
  splash_gradient: require("./images/background-gradient.png"),
  google_icon: require("@/assets/images/Google.png"),
  facebook_icon: require("@/assets/images/facebook.png"),
  authStart: require("@/assets/images/authStart.jpg"),
  welcomeScreen: require("@/assets/images/welcome-screen.png"),
  streakArm: require("@/assets/images/streakArm.png"),
  pillWithCircle: require("@/assets/images/pill-with-circle.png"),
  user: require("@/assets/images/user.png"),
  caps7: require("@/assets/images/caps7.png"),
  gym: require("@/assets/images/gym.png"),
  food: require("@/assets/images/food.png"),
  mind: require("@/assets/images/mind.png"),
  cover: {
    cover_1: require("@/assets/images/cover/cover-1.png"),
    cover_2: require("@/assets/images/cover/cover-2.png"),
    cover_3: require("@/assets/images/cover/cover-3.png"),
    cover_4: require("@/assets/images/cover/cover-4.png"),
    cover_5: require("@/assets/images/cover/cover-5.png"),
    cover_6: require("@/assets/images/cover/cover-6.png"),
    cover_7: require("@/assets/images/cover/cover-7.png"),
  },
};
